CA1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('buildings/', include('buildings.urls')),
    path('admin/', admin.site.urls),
]

buildings/urls.py
from django.urls import path

from . import views

app_name = 'buildings'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('sort-by/', views.SortDefaultView.as_view(), name='sort-by'),
    path('sort-by/pk/', views.SortPkView.as_view(), name='sort-by-pk'),
    path('sort-by/name/', views.SortNameView.as_view(), name='sort-by-name'),
    path('sort-by/address/', views.SortAdressView.as_view(), name='sort-by-address'),
    path('new/', views.NewBuildingView.as_view(), name='create'),
    path('detail/<int:pk>/', views.DetailBuildingView.as_view(), name='read'),
    path('modify/<int:pk>/', views.ModifyBuildingView.as_view(), name='update'),
    path('delete/<int:pk>/', views.DeleteBuildingView.as_view(), name='delete'),
]

buildings/models.py
from django.db import models
from django.urls import reverse


class Building(models.Model):
    name = models.CharField(max_length=50, default='Dorset College')
    floors = models.PositiveSmallIntegerField(default=1)
    color = models.CharField(max_length=50, default='Brick Red')
    residential = models.BooleanField(default=True)

    country = models.CharField(max_length=20, default='Ireland')
    city = models.CharField(max_length=20, default='Dublin')
    street = models.CharField(max_length=100, default='Belvedere Place, Mountjoy Square')
    number = models.CharField(max_length=10, default='7 & 8')

    def __str__(self):
        # return ', '. join([self.name, self.number, self.street, self.city, self.country])
        return self.name + ' (' + self.get_address1() + ')'

    def get_absolute_url(self):
        return reverse('buildings:read', kwargs={'pk': self.pk})

    def get_address1(self):
        return ', '.join([self.number, self.street, self.city, self.country])

    def get_address2(self):
        return ', '.join([self.country, self.city, self.street, self.number])

buildings/views.py
from django.urls import reverse
from django.views.generic import TemplateView, RedirectView, ListView, DetailView, CreateView, UpdateView, DeleteView

from .models import Building


class HomeView(TemplateView):
    template_name = "buildings/index.html"


class SortDefaultView(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        return reverse('buildings:sort-by-name')


class SortPkView(ListView):
    template_name = 'buildings/sort-by-pk.html'

    def get_queryset(self):
        # sort the buildings by primary key, highest first
        return Building.objects.order_by('-pk')


class SortNameView(ListView):
    template_name = 'buildings/sort-by-name.html'

    def get_queryset(self):
        # sort the buildings by alphabetical order of their name
        return Building.objects.order_by('name')


class SortAdressView(ListView):
    template_name = 'buildings/sort-by-address.html'

    def get_queryset(self):
        # sort the buildings by alphabetical order of their address
        return Building.objects.order_by('country', 'city', 'street', 'number')


class NewBuildingView(CreateView):
    template_name = 'buildings/create.html'
    model = Building
    # the 'fields' attribute says which field to display in which order
    fields = [
        'name',
        'country',
        'city',
        'street',
        'number',
        'floors',
        'color',
        'residential',
    ]

    def get_success_url(self):
        # the url to redirect to if the form is submitted
        return reverse('buildings:sort-by-pk')


class DetailBuildingView(DetailView):
    template_name = 'buildings/read.html'
    model = Building


class ModifyBuildingView(UpdateView):
    template_name = 'buildings/update.html'
    model = Building
    # the 'fields' attribute says which field to display in which order
    fields = [
        'name',
        'country',
        'city',
        'street',
        'number',
        'floors',
        'color',
        'residential',
    ]


class DeleteBuildingView(DeleteView):
    template_name = 'buildings/delete.html'
    model = Building

    def get_success_url(self):
        # the url to redirect to if the form is submitted
        return reverse('buildings:sort-by-name')

buildings/templates/buildings/create.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New | Buildings App</title>
    <link rel="stylesheet" href="{% static 'buildings/style.css' %}">
</head>
<body>
<header><h3>Buildings App | Antonin Suzor</h3></header>

<main>
<h1>Create a new building</h1>

<!-- 'form.as_p' generates a form based on the CreateView that calls the template -->
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create">
</form>

<p>
    <a href="{% url 'buildings:sort-by-name' %}">Back to list of buildings</a><br>
    <a href="{% url 'buildings:home' %}">Back to home page</a>
</p>
</main>
</body>
</html>

buildings/templates/buildings/delete.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete, {{ building.name }} | Buildings App</title>
    <link rel="stylesheet" href="{% static 'buildings/style.css' %}">
</head>
<body>
<header><h3>Buildings App | Antonin Suzor</h3></header>

<main>
<h1>Delete {{ building.name }}</h1>
<p>
    You may wish to:
    <a href="{% url 'buildings:create' %}">Create a new building</a>,
    <a href="{% url 'buildings:read' building.pk %}">Read details on this building</a>,
    <a href="{% url 'buildings:update' building.pk %}">Modify this building</a>.
</p>

<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ building }}"?</p>
    {{ form }}
    <input type="submit" value="Delete">
</form>

<p>
    <a href="{% url 'buildings:sort-by-name' %}">Back to list of buildings</a><br>
    <a href="{% url 'buildings:create' %}">Create a new building</a>
</p>
</main>
</body>
</html>

buildings/templates/buildings/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home | Buildings App</title>
    <link rel="stylesheet" href="{% static 'buildings/style.css' %}">
</head>
<body>
<header><h3>Buildings App | Antonin Suzor</h3></header>

<main>
<h1>Welcome to the <i>Buildings</i> App.</h1>

<p>
    This little database stores information about buildings.<br>
    In this version, you will be able to Create, Read, Update, and Delete buildings.<br>
    To start, please go to the
    <a href="{% url 'buildings:sort-by-name' %}">List of buildings</a> or
    <a href="{% url 'buildings:create' %}">Create a new building</a>.
</p>
</main>
</body>
</html>

buildings/templates/buildings/read.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Details, {{ building.name }} | Buildings App</title>
    <link rel="stylesheet" href="{% static 'buildings/style.css' %}">
</head>
<body>
<header><h3>Buildings App | Antonin Suzor</h3></header>

<main>
<h1>Details on {{ building.name }}</h1>
<p>
    You may wish to:
    <a href="{% url 'buildings:create' %}">Create a new building</a>,
    <a href="{% url 'buildings:update' building.pk %}">Modify this building</a>,
    <a href="{% url 'buildings:delete' building.pk %}">Delete this building</a>.
</p>

<p>
    This building is situated at {{ building.get_address1 }}.<br>
    Its signature color is {{ building.color }}, and it spans {{ building.floors }} floors.<br>
    <!-- the if statement allows smooth display of the 'residential' attribute -->
    It is {% if not building.residential %} not {% endif %} a residential building.<br>
    Its primary key in the database is {{ building.pk }}.
</p>

<p>
    <a href="{% url 'buildings:sort-by-name' %}">Back to list of buildings</a><br>
    <a href="{% url 'buildings:create' %}">Create a new building</a>
</p>
</main>
</body>
</html>

buildings/templates/buildings/sort-by-address.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SortBy, Address | Buildings App</title>
    <link rel="stylesheet" href="{% static 'buildings/style.css' %}">
</head>
<body>
<header><h3>Buildings App | Antonin Suzor</h3></header>

<main>
<h1>List of registered buildings, sorted by their address.</h1>
<p>
    You may wish to sort them by :
    <a href="{% url 'buildings:sort-by-pk' %}">Primary Key in the database</a> or by :
    <a href="{% url 'buildings:sort-by-name' %}">Name</a>
</p>

{% if building_list %}
    <ul>
    {% for building in building_list %}
        <li><a href="{% url 'buildings:read' building.pk %}" target="_blank">{{ building.name }}</a> -- {{ building.get_address2 }}</li><br>
    {% endfor %}
    </ul>
{% else %}
    <p>No buildings registered yet.</p>
{% endif %}

<p>
    <a href="{% url 'buildings:home' %}">Back to home page</a><br>
    <a href="{% url 'buildings:create' %}">Create a new building</a>
</p>
</main>
</body>
</html>

buildings/templates/buildings/sort-by-name.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SortBy, Name | Buildings App</title>
    <link rel="stylesheet" href="{% static 'buildings/style.css' %}">
</head>
<body>
<header><h3>Buildings App | Antonin Suzor</h3></header>

<main>
<h1>List of registered buildings, sorted by their name.</h1>
<p>
    You may wish to sort them by :
    <a href="{% url 'buildings:sort-by-pk' %}">Primary Key in the database</a> or by :
    <a href="{% url 'buildings:sort-by-address' %}">Address</a>
</p>

{% if building_list %}
    <ul>
    {% for building in building_list %}
        <li><a href="{% url 'buildings:read' building.pk %}" target="_blank">{{ building.name }}</a> -- {{ building.get_address2 }}</li><br>
    {% endfor %}
    </ul>
{% else %}
    <p>No buildings registered yet.</p>
{% endif %}

<p>
    <a href="{% url 'buildings:home' %}">Back to home page</a><br>
    <a href="{% url 'buildings:create' %}">Create a new building</a>
</p>
</main>
</body>
</html>

buildings/templates/buildings/sort-by-pk.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SortBy, Pk | Buildings App</title>
    <link rel="stylesheet" href="{% static 'buildings/style.css' %}">
</head>
<body>
<header><h3>Buildings App | Antonin Suzor</h3></header>

<main>
<h1>List of registered buildings, sorted by their primary key in the database.</h1>
<p>You may wish to sort them by : <a href="{% url 'buildings:sort-by-name' %}">their Name</a></p>

{% if building_list %}
    <ul>
    {% for building in building_list %}
        <li><a href="{% url 'buildings:read' building.pk %}", target="_blank">{{ building }}</a></li><br>
    {% endfor %}
    </ul>
{% else %}
    <p>No buildings registered yet.</p>
{% endif %}

<p>
    <a href="{% url 'buildings:home' %}">Back to home page</a><br>
    <a href="{% url 'buildings:create' %}">Create a new building</a>
</p>
</main>
</body>
</html>

buildings/templates/buildings/update.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Modify, {{ building.name }} | Buildings App</title>
    <link rel="stylesheet" href="{% static 'buildings/style.css' %}">
</head>
<body>
<header><h3>Buildings App | Antonin Suzor</h3></header>

<main>
<h1>Modify {{ building.name }}</h1>
<p>
    You may wish to:
    <a href="{% url 'buildings:create' %}">Create a new building</a>,
    <a href="{% url 'buildings:read' building.pk %}">Read details on this building</a>,
    <a href="{% url 'buildings:delete' building.pk %}">Delete this building</a>.
</p>

<!-- 'form.as_p' generates a form based on the UpdateView that calls the template -->
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>

<p>
    <a href="{% url 'buildings:sort-by-name' %}">Back to list of buildings</a><br>
    <a href="{% url 'buildings:create' %}">Create a new building</a>
</p>
</main>
</body>
</html>